# parameters for padded robot (not used for self collision checks)
default_robot_padding: 0.05
default_robot_scale: 1.0
default_robot_link_padding: 0.05
default_object_padding: 0.05
default_attached_padding: 0.05